# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Happo CI

on:
  pull_request:
    branches:
      - feature/**

jobs:
  happo:
    env:
      PREVIOUS_SHA: ${{ github.event.pull_request.base.sha }}
      CURRENT_SHA: ${{ github.event.pull_request.head.sha }}
      CHANGE_URL: ${{ github.event.pull_request.html_url }}
