# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Happo CI

on:
  pull_request:
    branches:
      - feature/**

jobs:
  happo:
    runs-on: ubuntu-latest

    env:
      PREVIOUS_SHA: ${{ github.event.pull_request.base.sha }}
      CURRENT_SHA: ${{ github.event.pull_request.head.sha }}
      CHANGE_URL: ${{ github.event.pull_request.html_url }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 8.x
        uses: actions/setup-node@v1
        with:
          node-version: 8.x
      - run: npm run happo-ci
        env:
          CI: true
